version: '3.8'

services:
  web:
    build: ./backend
    command: uvicorn api._api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    container_name : fast-api
    ports: 
      - 8000:8000

  frontend:
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/frontend
    environment: 
      HOST: 0.0.0.0
    ports: 
      - 3000:3000


